import { IDirectiveHandler, IDirective, DirectiveHandlerReturn, IRegion } from '../typedefs';
declare type OptionsHandler1Type = ((option: string, index?: number, list?: Array<string>) => void | boolean);
declare type OptionsHandler2Type<T> = ((options: T, option: string, index?: number, list?: Array<string>) => void | boolean);
export declare class DirectiveHandler implements IDirectiveHandler {
    protected key_: string;
    private handler_;
    private isMount_;
    private dataStorage_;
    private dataStorageCounter_;
    constructor(key_: string, handler_: (region: IRegion, element: HTMLElement, directive: IDirective) => DirectiveHandlerReturn, isMount_?: boolean);
    GetKey(): string;
    IsMount(): boolean;
    Handle(region: IRegion, element: HTMLElement, directive: IDirective): DirectiveHandlerReturn;
    Expunge(element: HTMLElement): void;
    protected AddStorage_(data: any, element?: HTMLElement): string;
    protected RemoveStorage_(key: string): void;
    static CreateProxy(getter: (prop: string) => any, contains: Array<string> | ((prop: string) => boolean), setter?: (prop: string | number | symbol, value: any, target?: object) => boolean, target?: any): any;
    static Evaluate(region: IRegion, element: HTMLElement, expression: string, ctxName?: string, ctx?: any, useWindow?: boolean): any;
    static EvaluateAlways(region: IRegion, element: HTMLElement, expression: string, ctxName?: string, ctx?: any, useWindow?: boolean): any;
    static BlockEvaluate(region: IRegion, element: HTMLElement, expression: string, ctxName?: string, ctx?: any, useWindow?: boolean): any;
    static BlockEvaluateAlways(region: IRegion, element: HTMLElement, expression: string, ctxName?: string, ctx?: any, useWindow?: boolean): any;
    static DoEvaluation(region: IRegion, element: HTMLElement, expression: string, ignoreRemoved: boolean, useBlock: boolean, ctxName?: string, ctx?: any, useWindow?: boolean): any;
    static Call(region: IRegion, callback: (...args: any) => any, ...args: any): any;
    static ExtractDuration(value: string, defaultValue: number): number;
    static ToString(value: any): string;
    static GetChildElementIndex(element: HTMLElement): number;
    static GetChildElementAt(region: IRegion, parent: HTMLElement, index: number, after?: HTMLElement): HTMLElement;
    static InsertOrAppendChildElement(region: IRegion, parent: HTMLElement, element: HTMLElement, index: number, after?: HTMLElement): void;
    static GetOptions<T>(options: T, specifiedOptions: Array<string>, handler?: OptionsHandler1Type, needsOptions?: false): T;
    static GetOptions<T>(options: T, specifiedOptions: Array<string>, handler?: OptionsHandler2Type<T>, needsOptions?: true): T;
    static IsEventRequest(key: string): boolean;
    static CheckEvents(key: string, region: IRegion, element: HTMLElement, directive: IDirective, defaultEvent?: string, events?: Array<string>): DirectiveHandlerReturn;
}
export {};
